version: '3.8'

services:
  app:
    build:
      dockerfile: docker/Dockerfile.dev
      context: .
      args:
        NODE_IMAGE: ${NODE_IMAGE}
    container_name: ${APP_NAME}-worker
    env_file:
      - .env
    command: sh -c "npm run dev"
    volumes:
      - ./:/home/app
      - ./node_modules:/home/app/node_modules
